spring.application.name=Security
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=newDB;trustServerCertificate=true
spring.datasource.username=SA
spring.datasource.password=Passwordls -la

spring.jpa.hibernate.ddl-auto=create
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE